=== Kushalpiya/coursera-course/catalog_19033685.dtd
<!ELEMENT musicStore (top_header,header,banner,banner_info,song)>
<!ELEMENT top_header (header_left,header_middle,header_right)>
<!ELEMENT header_left (header_leftimage,header_leftcontent)>
<!ELEMENT header_leftimage (#PCDATA)>
<!ELEMENT header_leftcontent (#PCDATA)>
<!ELEMENT header_middle (header_middleimage,header_middlecontent)>
<!ELEMENT header_middleimage (#PCDATA)>
<!ELEMENT header_middlecontent (#PCDATA)>
<!ELEMENT header_right (header_rightimage,header_rightcontent)>
<!ELEMENT header_rightimage (#PCDATA)>
<!ELEMENT header_rightcontent (#PCDATA)>
<!ELEMENT header (logo,slogandiv,abs)>
<!ELEMENT logo (#PCDATA)>
<!ELEMENT abs (#PCDATA)>
<!ELEMENT slogandiv (slogan)>
<!ELEMENT slogan (#PCDATA | span)*>
<!ELEMENT span (#PCDATA)>
<!ELEMENT banner (banner_content)>
<!ELEMENT banner_content (#PCDATA)>
<!ELEMENT banner_info (#PCDATA) >
<!ELEMENT song (songs+)>
<!ELEMENT songs (coverPhoto,songgrid)>
<!ELEMENT coverPhoto (#PCDATA)>
<!ELEMENT songgrid (songDescription,award?)>
<!ELEMENT songDescription (info1,info2?,info3?,info4?,info5?,info6)>
<!ELEMENT info1 (nametitle,name)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT info2 (nametitle,genre)>
<!ELEMENT genre (#PCDATA)>
<!ELEMENT info3 (nametitle,producerName)>
<!ELEMENT producerName (#PCDATA)>
<!ELEMENT info4 (nametitle,singer)>
<!ELEMENT singer (#PCDATA)>
<!ELEMENT info5 (nametitle,releaseYear)>
<!ELEMENT releaseYear (#PCDATA)>
<!ELEMENT info6 (nametitle,timeLength)>
<!ELEMENT timeLength (#PCDATA)>
<!ELEMENT nametitle (#PCDATA)>
<!ELEMENT award (nametitle?,info?)>
<!ELEMENT info (nametitle,award1*)>
<!ELEMENT award1 (image,name)>
<!ELEMENT image (#PCDATA)>
<!ATTLIST header_leftcontent address CDATA #REQUIRED>
<!ATTLIST header_middlecontent web CDATA #REQUIRED>
<!ATTLIST header_rightcontent contact CDATA #REQUIRED>
<!ATTLIST songs id CDATA #REQUIRED>
<!ATTLIST coverPhoto song CDATA #IMPLIED>
<!ATTLIST releaseYear releaseDate CDATA #IMPLIED>

=== Kushalpiya/coursera-course/catalog_19033685.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<?xml-stylesheet type="text/css" href="catalog_19033685.css"?>
<!-- <!DOCTYPE musicStore SYSTEM "catalog_19033685.dtd"> -->
<musicStore xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="catalog_19033685.xsd">
    <top_header>
        <header_left>
            <header_leftimage/>
            <header_leftcontent address="A01">Gongabu,Kathmandu</header_leftcontent>
        </header_left>
        <header_middle>
            <header_middleimage/>
            <header_middlecontent web="W2">http://www.programusic.com</header_middlecontent>
        </header_middle>
        <header_right>
            <header_rightimage/>
            <header_rightcontent contact="Phone">+977 9841414141</header_rightcontent>
        </header_right>
    </top_header>
    <header>
        <logo/>
        <slogandiv>
            <slogan>
                Let the
                <span>Music</span>
                Speak!
            </slogan>
        </slogandiv>
        <abs/>
    </header>
    <banner>
        <banner_content>PROGRAMUSIC</banner_content>
    </banner>
    <banner_info>
        Note: Hover on the cards to see the awards.
    </banner_info>
    <song>
        <songs id="S01">
            <coverPhoto song="C1"/>
            <songgrid>
                <songDescription>
                    <info1>
                        <nametitle>Song Name:</nametitle>
                        <name>Despacito</name>
                    </info1>
                    <info2>
                        <nametitle>Genre:</nametitle>
                        <genre>Pop</genre>
                    </info2>
                    <info3>
                        <nametitle>Producer:</nametitle>
                        <producerName>Mauricio Rengifo</producerName>
                    </info3>
                    <info4>
                        <nametitle>Singer:</nametitle>
                        <singer>Luis Fonsi</singer>
                    </info4>
                    <info5>
                        <nametitle>Release Date:</nametitle>
                        <releaseYear releaseDate="year">2017</releaseYear>
                    </info5>
                    <info6>
                        <nametitle>Time Length:</nametitle>
                        <timeLength>4mins 42seconds</timeLength>
                    </info6>
                </songDescription>
                <award>
                    <info>
                        <nametitle>Awards:</nametitle>
                        <award1>
                            <image/>
                            <name>Grammy Award</name>
                        </award1>
                        <award1>
                            <image/>
                            <name>Kids' Choice Award</name>
                        </award1>
                        <award1>
                            <image/>
                            <name>Billboard Music Award</name>
                        </award1>
                        <award1>
                            <image/>
                            <name>American Music Award</name>
                        </award1>
                        <award1>
                            <image/>
                            <name>iHeartRadio Music Award</name>
                        </award1>
                    </info>
                </award>
            </songgrid>
        </songs>
        <songs id="S02">
            <coverPhoto song="C2"/>
            <songgrid>
                <songDescription>
                    <info1>
                        <nametitle>Song Name:</nametitle>
                        <name>Dynamite</name>
                    </info1>
                    <info2>
                        <nametitle>Genre:</nametitle>
                        <genre>Pop</genre>
                    </info2>
                    <info3>
                        <nametitle>Producer:</nametitle>
                        <producerName>David Stewart</producerName>
                    </info3>
                    <info4>
                        <nametitle>Singer:</nametitle>
                        <singer>BTS</singer>
                    </info4>
                    <info5>
                        <nametitle>Release Date:</nametitle>
                        <releaseYear releaseDate="year">2020</releaseYear>
                    </info5>
                    <info6>
                        <nametitle>Time Length:</nametitle>
                        <timeLength>3mins 44seconds</timeLength>
                    </info6>
                </songDescription>
                <award>
                    <info>
                        <nametitle>Awards:</nametitle>
                        <award1>
                            <image/>
                            <name>People's Choice Award</name>
                        </award1>
                        <award1>
                            <image/>
                            <name>Golden Disc Award</name>
                        </award1>
                        <award1>
                            <image/>
                            <name>Mnet Asian Music Award</name>
                        </award1>
                        <award1>
                            <image/>
                            <name>MTV Europe Music Award</name>
                        </award1>
                        <award1>
                            <image/>
                            <name>Kids' Choice Award</name>
                        </award1>
                    </info>
                </award>
            </songgrid>
        </songs>
        <songs id="S03">
            <coverPhoto song="C3"/>
            <songgrid>
                <songDescription>
                    <info1>
                        <nametitle>Song Name:</nametitle>
                        <name>Can't Help Falling In Love</name>
                    </info1>
                    <info2>
                        <nametitle>Genre:</nametitle>
                        <genre>Pop</genre>
                    </info2>
                    <info3>
                        <nametitle>Producer:</nametitle>
                        <producerName>Elvis Presley</producerName>
                    </info3>
                    <info4>
                        <nametitle>Singer:</nametitle>
                        <singer>Elvis Presley</singer>
                    </info4>
                    <info5>
                        <nametitle>Release Date:</nametitle>
                        <releaseYear releaseDate="year">1961</releaseYear>
                    </info5>
                    <info6>
                        <nametitle>Time Length:</nametitle>
                        <timeLength>2mins 59seconds</timeLength>
                    </info6>
                </songDescription>
                <award>
                    <info>
                        <nametitle>Awards:</nametitle>
                        <award1>
                            <image/>
                            <name>Grammy Award</name>
                        </award1>
                        <award1>
                            <image/>
                            <name>Kids Choice Award</name>
                        </award1>
                        <award1>
                            <image/>
                            <name>Billboard Music Award</name>
                        </award1>
                        <award1>
                            <image/>
                            <name>American Music Award</name>
                        </award1>
                        <award1>
                            <image/>
                            <name>iHeartRadio Music Award</name>
                        </award1>
                    </info>
                </award>
            </songgrid>
        </songs>
        <songs id="S04">
            <coverPhoto song="C4"/>
            <songgrid>
                <songDescription>
                    <info1>
                        <nametitle>Song Name:</nametitle>
                        <name>So What</name>
                    </info1>
                    <info2>
                        <nametitle>Genre:</nametitle>
                        <genre>Jazz</genre>
                    </info2>
                    <info3>
                        <nametitle>Producer:</nametitle>
                        <producerName>Teo Macero</producerName>
                    </info3>
                    <info4>
                        <nametitle>Singer:</nametitle>
                        <singer>Miles Davis</singer>
                    </info4>
                    <info5>
                        <nametitle>Release Date:</nametitle>
                        <releaseYear releaseDate="year">1959</releaseYear>
                    </info5>
                    <info6>
                        <nametitle>Time Length:</nametitle>
                        <timeLength>9mins 22seconds</timeLength>
                    </info6>
                </songDescription>
                <award>
                    <info>
                        <nametitle>Awards:</nametitle>
                        <award1>
                            <image/>
                            <name>Best Large Jazz Ensemble Album</name>
                        </award1>
                        <award1>
                            <image/>
                            <name>Grammy Hall of Fame</name>
                        </award1>
                        <award1>
                            <image/>
                            <name>Porin Award</name>
                        </award1>
                        <award1>
                            <image/>
                            <name>American Book Award</name>
                        </award1>
                        <award1>
                            <image/>
                            <name>NAACP Image Award</name>
